import NavBarComponent from "../components/NavBarComponent";
import SideBar from "../components/SideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Dashboard({ children }) {
  return (
    <>
      <div className="h-screen">
        <NavBarComponent />
        <div className="flex justify-between gap-9 h-full">
          <div className="w-1/4 h-full ">
            <SideBar />
          </div>
          <div className="w-3/4 p-4 mt-10 align-center h-full overflow-y-auto">
            {children}
          </div>
        </div>
      </div>
    </>
  );
}
